"""add pins and home tab

Revision ID: 3707eb3f2230
Revises: 7d96ccdb0f6d
Create Date: 2026-09-22 17:37:50.759310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3707eb3f2230'
down_revision: Union[str, Sequence[str], None] = '7d96ccdb0f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pins_id'), 'pins', ['id'], unique=False)
    op.create_index(op.f('ix_pins_user_id'), 'pins', ['user_id'], unique=False)
    op.create_index(op.f('ix_pins_widget_id'), 'pins', ['widget_id'], unique=False)
    op.add_column('tabs', sa.Column('is_home', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Backfill: każde istniejące konto dostaje stronę główną - nowe konta
    # dostają ją już przy rejestracji (routers/auth.py), ale to nie dotyczy
    # kont założonych przed tą migracją.
    op.execute(
        """
        INSERT INTO tabs (user_id, name, color, position, is_home, created_at)
        SELECT id, 'Strona główna', '#3fbf94', 0, true, now()
        FROM users
        WHERE id NOT IN (SELECT user_id FROM tabs WHERE is_home)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM tabs WHERE is_home")
    op.drop_column('tabs', 'is_home')
    op.drop_index(op.f('ix_pins_widget_id'), table_name='pins')
    op.drop_index(op.f('ix_pins_user_id'), table_name='pins')
    op.drop_index(op.f('ix_pins_id'), table_name='pins')
    op.drop_table('pins')
    # ### end Alembic commands ###
