"""add tabs, widgets, widget_entries

Revision ID: 7d96ccdb0f6d
Revises: 
Create Date: 2026-08-20 06:55:52.435626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d96ccdb0f6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabs_id'), 'tabs', ['id'], unique=False)
    op.create_index(op.f('ix_tabs_user_id'), 'tabs', ['user_id'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single_value', 'table', 'formula', 'currency', name='widget_type'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(op.f('ix_widgets_tab_id'), 'widgets', ['tab_id'], unique=False)
    op.create_table('widget_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_entries_id'), 'widget_entries', ['id'], unique=False)
    op.create_index(op.f('ix_widget_entries_widget_id'), 'widget_entries', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_entries_widget_id'), table_name='widget_entries')
    op.drop_index(op.f('ix_widget_entries_id'), table_name='widget_entries')
    op.drop_table('widget_entries')
    op.drop_index(op.f('ix_widgets_tab_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_tabs_user_id'), table_name='tabs')
    op.drop_index(op.f('ix_tabs_id'), table_name='tabs')
    op.drop_table('tabs')
    # ### end Alembic commands ###
