"""add user profile fields

Revision ID: b8be7b6fca8c
Revises: 3707eb3f2230
Create Date: 2026-09-23 10:47:15.041611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8be7b6fca8c'
down_revision: Union[str, Sequence[str], None] = '3707eb3f2230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_icon')
    op.drop_column('users', 'avatar_color')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
